# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dendrogramm
import HeatMap
#from Ui_Form import Ui_OtherWindow()
from UI.dendrogramm import Ui_dendrogramm
from UI.HeatMap import Ui_HeatMap


class Ui_MainWindow(object):
    # mein code (start)
    def openWindow_den(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_dendrogramm()
        self.ui.setupUi(self.window)
        self.window.show()

    def openWindow_heat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_HeatMap()
        self.ui.setupUi(self.window)
        self.window.show()

        #ende

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 419)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 230, 81, 31))
        self.pushButton.setObjectName("pushButton")
        # mein code start
        self.pushButton.clicked.connect(self.openWindow_den)
        #mein code ende
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 230, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        # mein code start
        self.pushButton_2.clicked.connect(self.openWindow_heat)
        # mein code ende

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 180, 101, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 180, 101, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(201, 61, 128, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(320, 60, 41, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 100, 61, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 100, 51, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(260, 140, 80, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionfrom_the_local = QtWidgets.QAction(MainWindow)
        self.actionfrom_the_local.setObjectName("actionfrom_the_local")
        self.actionfrom_the_internet = QtWidgets.QAction(MainWindow)
        self.actionfrom_the_internet.setObjectName("actionfrom_the_internet")
        self.actionDendrogramm = QtWidgets.QAction(MainWindow)
        self.actionDendrogramm.setObjectName("actionDendrogramm")
        self.actionHeat_Map = QtWidgets.QAction(MainWindow)
        self.actionHeat_Map.setObjectName("actionHeat_Map")
        self.actionHistory = QtWidgets.QAction(MainWindow)
        self.actionHistory.setObjectName("actionHistory")
        self.menuFile.addAction(self.actionfrom_the_local)
        self.menuFile.addAction(self.actionfrom_the_internet)
        self.menuHelp.addAction(self.actionHistory)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "generate1"))
        self.pushButton_2.setText(_translate("MainWindow", "generate2"))
        self.label.setText(_translate("MainWindow", "Dendrogramm:"))
        self.label_2.setText(_translate("MainWindow", "Heat-Map:"))
        self.label_3.setText(_translate("MainWindow", "Number of clusters:"))
        self.label_4.setText(_translate("MainWindow", "Direction:"))
        self.checkBox_2.setText(_translate("MainWindow", "Colored"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionfrom_the_local.setText(_translate("MainWindow", "from the local"))
        self.actionfrom_the_internet.setText(_translate("MainWindow", "from the  internet"))
        self.actionDendrogramm.setText(_translate("MainWindow", "Dendrogramm"))
        self.actionHeat_Map.setText(_translate("MainWindow", "Heat Map"))
        self.actionHistory.setText(_translate("MainWindow", "History"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
